Referencia a lo que sigue: [quickstart](https://numpy.org/doc/stable/user/quickstart.html) y [Numerical Python by Robert Johansson, Apress](https://www.apress.com/gp/book/9781484242452).

La mayor cantidad de problemas que surgen en aplicaciones se resuelven con cómputo numérico y no con cómputo simbólico o algebraico. El paquete de [NumPy](https://numpy.org/) ayuda al cómputo numérico.

Lo que podemos encontrar en *Numpy*:

* Objetos *array* n-dimensionales.

* Funciones para cálculos numéricos típicos en el Álgebra lineal, Cálculo, Probabilidad y Estadística. 

In [1]:
import numpy as np #utilizamos un alias con la palabra reservada "as"

Una vez hecho el `import` podemos utilizar una gran variedad de funciones en este paquete. 

Lo más sencillo es iniciar con formas para crear *arrays* de *NumPy*.

En lo que continúa se utiliza el nombre de *array* para un *array* de *NumPy*.

# Crear *arrays*

## Con listas de Python

Podemos usar listas en Python para crear *arrays*:

In [2]:
l = [1,2,3,4,5,6,7,8,9,10]
v = np.array(l)
v

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**Recuerda que una lista en Python es una estructura de datos.**

Cada *array* tiene **atributos** como: `ndim` (número de *axes* o ejes), `shape` (tamaño de cada eje), `size` (el tamaño total del *array*) y `dtype` el **tipo** de **valor** que el *array* almacena.

In [3]:
print('v.ndim:', v.ndim) #usamos un punto para acceder a los atributos
print('v.shape:', v.shape)
print('v.size:', v.size)
print('v.dtype', v.dtype)

v.ndim: 1
v.shape: (10,)
v.size: 10
v.dtype int64


**Obsérvese que el tipo de valor que almacena el *array* es `int64`**. Si queremos crear un *array* que almacene valor tipo `float` podemos especificar el atributo `dtype` al crear el *array*:

In [4]:
v = np.array(l,dtype = float)
v

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [5]:
print('v.dtype', v.dtype)

v.dtype float64


Otra forma de crear un *array* que almacene un valor de tipo `float` es:

In [6]:
l = [1,2,3,4,5,6,7,8,9,10.0] #el último elemento es 10.0
v = np.array(l)
v

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [7]:
print('v.dtype', v.dtype)

v.dtype float64


Usamos la función `type` para ver el tipo del objeto al que hace referencia la variable `v`:

In [8]:
type(v)

numpy.ndarray

y es un tipo de la clase [ndarray](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html).

**Obsérvese** que los valores de cada *array* deben ser del mismo tipo, ser **homogéneos**, esto es, hay que tener cuidado al crear un *array*:

In [9]:
v2 = np.array([2.0, "hola"])

In [10]:
v2

array(['2.0', 'hola'], dtype='<U32')

In [11]:
v2.dtype 

dtype('<U32')

pues aunque sí podemos crear un *array* con un `float` y un `string`, el tipo que resulta hace referencia a *little-endian Unicode string of 32 characters*. Ver: [liga](https://stackoverflow.com/questions/56944812/how-to-interpret-python-output-dtype-u32/56944839), [liga2](https://numpy.org/doc/stable/reference/arrays.dtypes.html).

## Con funciones de *NumPy*

In [12]:
np.ones(3)

array([1., 1., 1.])

In [13]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [17]:
np.linspace(0,1,2)

array([0., 1.])

In [18]:
np.linspace(0,1,3)

array([0. , 0.5, 1. ])

In [19]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [20]:
np.arange(4)

array([0, 1, 2, 3])

In [21]:
np.arange(-2,5)

array([-2, -1,  0,  1,  2,  3,  4])

In [22]:
np.arange(-2, 6, 2)

array([-2,  0,  2,  4])

In [23]:
np.arange(0, 1, .2)

array([0. , 0.2, 0.4, 0.6, 0.8])

## *Arrays* con dos ejes (*axes*) o 2-dimensionales

In [24]:
A = np.array([[1,2,3],
              [4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
print('A.ndim:', A.ndim)
print('A.shape:', A.shape)
print('A.size:', A.size)
print('A.dtype', A.dtype)

A.ndim: 2
A.shape: (2, 3)
A.size: 6
A.dtype int64


In [26]:
A = np.array([[1,2,3],
              [4,5,6.0]])
A

array([[1., 2., 3.],
       [4., 5., 6.]])

In [27]:
print('A.ndim:', A.ndim)
print('A.shape:', A.shape)
print('A.size:', A.size)
print('A.dtype', A.dtype)

A.ndim: 2
A.shape: (2, 3)
A.size: 6
A.dtype float64


## Accesar a los valores de un *array*

El primer elemento del *array* tiene índice 0 a diferencia de otros lenguajes de programación como *MATLAB* o *R*.

Accedemos con **corchetes**:

In [28]:
print('primer valor', v[0])
print('último valor', v[-1])
print('segundo valor', v[1])
print('penúltimo valor', v[-2])
print('del primero al 2º valor incluyendo este último', v[:2])
print('del 2º al último valor sin incluir el 2º', v[2:])
print('del 1er valor al último elemento de 2 en 2', v[0:10:2])

primer valor 1.0
último valor 10.0
segundo valor 2.0
penúltimo valor 9.0
del primero al 2º valor incluyendo este último [1. 2.]
del 2º al último valor sin incluir el 2º [ 3.  4.  5.  6.  7.  8.  9. 10.]
del 1er valor al último elemento de 2 en 2 [1. 3. 5. 7. 9.]


In [29]:
idx = [0, 4, 9]

In [30]:
print('imprimiento algunos índices:', v[idx])

imprimiento algunos índices: [ 1.  5. 10.]


**2-dimensionales:**

In [31]:
A

array([[1., 2., 3.],
       [4., 5., 6.]])

In [32]:
print('valor en la posición (0,0):', A[0][0])
print('valor en la posición (1,2):', A[1][2])
#también con la siguiente notación:
print('valor en la posición (0,0):', A[0,0])
print('valor en la posición (1,2):', A[1,2])

valor en la posición (0,0): 1.0
valor en la posición (1,2): 6.0
valor en la posición (0,0): 1.0
valor en la posición (1,2): 6.0


In [33]:
print('primer columna:', A[:,0])
print('tercer columna:', A[:,2])
print('segundo renglón:', A[1,:])

primer columna: [1. 4.]
tercer columna: [3. 6.]
segundo renglón: [4. 5. 6.]


## Reshape

In [34]:
v = np.array([1,2,3,4,5])

In [35]:
v.shape

(5,)

In [36]:
v.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [37]:
v.reshape(1,5).shape

(1, 5)

In [38]:
v.reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [39]:
v.reshape(5,1).shape

(5, 1)

# Operaciones en el álgebra lineal con numpy

## Producto escalar-vector, suma y punto entre vectores

In [40]:
v1 = np.array([6,-3,4])
v2 = np.array([4,5,0])
scalar = -1/2

In [41]:
scalar*v1

array([-3. ,  1.5, -2. ])

In [42]:
v1.dot(v2)

9

In [43]:
v1+v2

array([10,  2,  4])

## Producto matriz vector point-wise

In [44]:
A = np.array([[2,5,0],
              [3,6,6],
              [-6,4,-1],
              [5,4,9.0]])
A

array([[ 2.,  5.,  0.],
       [ 3.,  6.,  6.],
       [-6.,  4., -1.],
       [ 5.,  4.,  9.]])

In [45]:
v = np.array([-2,1,4])
v

array([-2,  1,  4])

In [46]:
A*v #cada columna es multiplicada por las entradas de v

array([[ -4.,   5.,   0.],
       [ -6.,   6.,  24.],
       [ 12.,   4.,  -4.],
       [-10.,   4.,  36.]])

In [47]:
A

array([[ 2.,  5.,  0.],
       [ 3.,  6.,  6.],
       [-6.,  4., -1.],
       [ 5.,  4.,  9.]])

In [48]:
v = np.array([-1, 2, 1, 0])
v

array([-1,  2,  1,  0])

In [49]:
v*A #no es posible hacer este producto por diferencias entre shapes

ValueError: operands could not be broadcast together with shapes (4,) (4,3) 

In [50]:
v.reshape(4,1)

array([[-1],
       [ 2],
       [ 1],
       [ 0]])

In [51]:
v.reshape(4,1)*A #cada renglón es multiplicado por las entradas de v

array([[-2., -5., -0.],
       [ 6., 12., 12.],
       [-6.,  4., -1.],
       [ 0.,  0.,  0.]])

## Producto matriz-vector

In [52]:
A = np.array([[2,5,0],
              [3,6,6],
              [-6,4,-1],
              [5,4,9]])
A

array([[ 2,  5,  0],
       [ 3,  6,  6],
       [-6,  4, -1],
       [ 5,  4,  9]])

In [53]:
v = np.array([-2,1.0,4])
v

array([-2.,  1.,  4.])

In [54]:
A.dot(v)

array([ 1., 24., 12., 30.])

In [55]:
A@v

array([ 1., 24., 12., 30.])

In [56]:
v = np.array([7,0,-3,2])
v

array([ 7,  0, -3,  2])

In [57]:
v@A

array([42, 31, 21])

**Obs:** obsérvese en este último ejemplo que no fue necesario indicar que tenemos un vector renglón para realizar por la izquierda la multiplicación: $vA$.

## Suma y producto matriz-matriz pointwise

In [58]:
A = np.array([[2,5,0],
              [3,6,6],
              [-6,4,-1],
              [5,4,9]])
A

array([[ 2,  5,  0],
       [ 3,  6,  6],
       [-6,  4, -1],
       [ 5,  4,  9]])

In [59]:
B = np.array([[2,-2,3],
              [1,-1,5],
              [0,-2,1.0],
              [0,0,-3]])
B

array([[ 2., -2.,  3.],
       [ 1., -1.,  5.],
       [ 0., -2.,  1.],
       [ 0.,  0., -3.]])

In [60]:
A+B

array([[ 4.,  3.,  3.],
       [ 4.,  5., 11.],
       [-6.,  2.,  0.],
       [ 5.,  4.,  6.]])

In [61]:
A*B

array([[  4., -10.,   0.],
       [  3.,  -6.,  30.],
       [ -0.,  -8.,  -1.],
       [  0.,   0., -27.]])

## Producto matriz-matriz

In [62]:
A = np.array([[2,5,0],
              [3,6,6],
              [-6,4,-1],
              [5,4,9]])
A

array([[ 2,  5,  0],
       [ 3,  6,  6],
       [-6,  4, -1],
       [ 5,  4,  9]])

In [63]:
B = np.array([[2,-2,3],
              [1,-1,5],
              [0,-2,1]])
B

array([[ 2, -2,  3],
       [ 1, -1,  5],
       [ 0, -2,  1]])

In [64]:
A@B

array([[  9,  -9,  31],
       [ 12, -24,  45],
       [ -8,  10,   1],
       [ 14, -32,  44]])

# Resolver sistema de ecuaciones lineales


$$\begin{array}{ccc} 8x_1 -6x_2 + 2x_3  &= & 28 \\ -4x_1 + 11x_2 -7x_3 &= & -40 \\ 4x_1 -7x_2 + 6x_3 &=& 33\end{array} $$

In [65]:
A = np.array([[8, -6, 2], 
              [-4, 11, -7], 
              [4, -7, 6.0]])
b = np.array([28,-40,33.0])

In [66]:
A

array([[ 8., -6.,  2.],
       [-4., 11., -7.],
       [ 4., -7.,  6.]])

In [67]:
b

array([ 28., -40.,  33.])

Usamos la función de [solve](https://numpy.org/doc/stable/reference/generated/numpy.linalg.solve.html) dentro de [numpy.linalg](https://numpy.org/doc/stable/reference/routines.linalg.html)

In [68]:
x=np.linalg.solve(A,b)

In [69]:
x

array([ 2., -1.,  3.])

In [70]:
print('Verificando resultado Ax = b')
print('b:')
b


Verificando resultado Ax = b
b:


array([ 28., -40.,  33.])

In [71]:
print('Ax:')
A@x

Ax:


array([ 28., -40.,  33.])